version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-api-prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
      MYSQL_DATABASE: agendamentoapi
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: Senha123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - agendamento-net

  api:
    image: agendamentoapi
    container_name: agendamento-api-final
    restart: always
    depends_on:
      - mysql
    ports:
      - "5004:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Server=mysql-api-prod;Port=3306;Database=agendamentoapi;User=apiuser;Password=Senha123;
    networks:
      - agendamento-net

volumes:
  mysql_data:

networks:
  agendamento-net:
    driver: bridge

